version: '3.8'

services:

  api:
    image: ghcr.io/silkkycloud/vaultwarden:1.23.0
    hostname: vaultwarden
    networks:
      - public
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main-3"
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.2'
          memory: 512M
    volumes:
      - data:/data
      - attachments:/vw-attachments
      - sends:/vw-sends
      - icons_cache:/vw-icon-cache
    environment:
      # Database
      - DATABASE_URL=postgresql://bitwarden:${POSTGRESQL_PASSWORD}@postgresql:5432/bitwarden
      - ENABLE_DB_WAL=false
      # General
      - DOMAIN=https://${BITWARDEN_HOSTNAME}
      - SIGNUPS_ALLOWED=true
      - IP_HEADER=X-Forwarded-For
      - LOG_FILE=/data/bitwarden.log
      # Email
      - SMTP_HOST=${MAIL_HOST}
      - SMTP_FROM=${MAIL_FROM}
      - SMTP_FROM_NAME=${MAIL_FROM_NAME}
      - SMTP_PORT=${MAIL_PORT}
      - SMTP_USERNAME=${MAIL_USERNAME}
      - SMTP_PASSWORD=${MAIL_PASSWORD}
      - SMTP_AUTH_MECHANISM="login"
      # Admin
      #- ADMIN_TOKEN=${ADMIN_TOKEN}
      # Websocket notifications
      - WEBSOCKET_ENABLED=true
      # Sends
      - SENDS_ALLOWED=true
      # HaveIBeenPwned API Key
      - HIBP_API_KEY=${HIBP_KEY}

  web:
    image: ghcr.io/silkkycloud/vaultwarden-web:2.24.1
    hostname: vaultwarden-web
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - "node.hostname == main-3"
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

  postgresql:
    image: postgres:14-alpine
    hostname: postgresql
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main-3"
      resources:
        limits:
          cpus: '1'
          memory: 4G
        reservations:
          cpus: '0.2'
          memory: 512M
    volumes:
      - database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=bitwarden
      - POSTGRES_USER=bitwarden
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}

networks:
  public:
    external: true
  
  backend:
    driver: overlay
    internal: true
    driver_opts:
      encrypted: "true"
      com.docker.network.driver.mtu: 1450

volumes:
  database:
  data:
  attachments:
  sends:
  icons_cache: