# Can be a tag, release, but prefer a commit hash because it's not changeable
# https://github.com/bitwarden/web/commit/$VAULT_VERSION
#
# Using https://github.com/bitwarden/web/releases/tag/v2.24.1
ARG VAULT_VERSION=a6274fa56ec869a5c981c2edfff9db87a3bca4bf

####################################################################################################
## Builder
####################################################################################################
FROM node:14-alpine3.14 AS builder

# Update NPM - Matching the bitwarden/web GH Action Workflow.
RUN npm -g install npm@7

RUN apk add --no-cache \
    git \
    bash

# Prepare the folder to enable non-root, otherwise npm will refuse to run the postinstall
WORKDIR /vault
RUN chown -R node:node /vault
USER node

RUN git clone https://github.com/bitwarden/web.git /vault

RUN git checkout "$VAULT_VERSION" \
    && git submodule update --recursive --init

# Get the patches
RUN git clone https://github.com/dani-garcia/bw_web_builds.git /tmp/bw_web_builds

RUN cp -r /tmp/bw_web_builds/patches /patches \
    && cp -r /tmp/bw_web_builds/apply_patches.sh /apply_patches.sh

RUN chown -R node:node /patches \
    && chown -R node:node /apply_patches.sh

RUN bash /apply_patches.sh

RUN rm -rf /tmp/bw_web_builds

# Build
RUN npm ci --legact-peer-deps
RUN npm audit fix --legacy-peer-deps || true
RUN npm run dist:oss:selfhost

RUN printf '{"version":"%s"}' \
      $(git -c 'versionsort.suffix=-' ls-remote --tags --sort='v:refname' https://github.com/dani-garcia/bw_web_builds.git 'v*' | tail -n1 | sed -E 's#.*?refs/tags/v##') \
      > build/bwrs-version.json

# Prepare final archives
RUN mv build web-vault

####################################################################################################
## Final image
####################################################################################################
# We copy the final result as a separate empty image so there's no need to download all the intermediate steps
FROM scratch

COPY --from=builder /vault/web-vault /web-vault
# Added so docker create works, can't actually run a scratch image
CMD [""]